import { createSlice } from "@reduxjs/toolkit";
import { filterList } from "../utils/filterList.js";

const initialState = {
  list: [
    {
      firstName: "John",
      lastName: "Doe",
      startDate: "2022-01-01",
      department: "Sales",
      birthDate: "1990-01-01",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    {
      firstName: "Jane",
      lastName: "Smith",
      startDate: "2022-01-01",
      department: "Marketing",
      birthDate: "1995-01-01",
      street: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
    },
    {
      firstName: "Michael",
      lastName: "Johnson",
      startDate: "2022-01-01",
      department: "Engineering",
      birthDate: "1985-01-01",
      street: "789 Elm St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    {
      firstName: "Emily",
      lastName: "Davis",
      startDate: "2022-01-01",
      department: "Finance",
      birthDate: "1992-01-01",
      street: "321 Pine Rd",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
    },
    {
      firstName: "David",
      lastName: "Wilson",
      startDate: "2022-01-01",
      department: "Human Resources",
      birthDate: "1988-01-01",
      street: "654 Cedar Ln",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
    },
    {
      firstName: "Sarah",
      lastName: "Miller",
      startDate: "2022-01-01",
      department: "Operations",
      birthDate: "1993-01-01",
      street: "987 Maple Dr",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19103",
    },
    {
      firstName: "John",
      lastName: "Doe",
      startDate: "2022-01-01",
      department: "Sales",
      birthDate: "1990-01-01",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    {
      firstName: "Jane",
      lastName: "Smith",
      startDate: "2022-01-01",
      department: "Marketing",
      birthDate: "1995-01-01",
      street: "456 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
    },
    {
      firstName: "Michael",
      lastName: "Johnson",
      startDate: "2022-01-01",
      department: "Engineering",
      birthDate: "1985-01-01",
      street: "789 Elm St",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    {
      firstName: "Emily",
      lastName: "Davis",
      startDate: "2022-01-01",
      department: "Finance",
      birthDate: "1992-01-01",
      street: "321 Pine Rd",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
    },
    {
      firstName: "David",
      lastName: "Wilson",
      startDate: "2022-01-01",
      department: "Human Resources",
      birthDate: "1988-01-01",
      street: "654 Cedar Ln",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
    },
    {
      firstName: "Sarah",
      lastName: "Miller",
      startDate: "2022-01-01",
      department: "Operations",
      birthDate: "1993-01-01",
      street: "987 Maple Dr",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19103",
    },
    {
      firstName: "Robert",
      lastName: "Brown",
      startDate: "2022-01-01",
      department: "IT",
      birthDate: "1987-01-01",
      street: "147 Birch St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
    },
    {
      firstName: "Lisa",
      lastName: "Taylor",
      startDate: "2022-01-01",
      department: "HR",
      birthDate: "1991-01-01",
      street: "258 Spruce Ln",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    {
      firstName: "James",
      lastName: "Anderson",
      startDate: "2022-01-01",
      department: "Legal",
      birthDate: "1989-01-01",
      street: "369 Willow Rd",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
  ],
  searchResult: "",
  currentPage: 1,
  entriesPerPage: 10,
  sortConfig: { key: null, direction: "asc" },
};

const tableSlice = createSlice({
  name: "table",
  initialState,
  reducers: {
    setSearchResult: (state, action) => {
      state.searchResult = action.payload;
      state.list = filterList(initialState.list, action.payload);
    },
    setCurrentPage: (state, action) => {
      state.currentPage = action.payload;
    },
    setEntriesPerPage: (state, action) => {
      state.entriesPerPage = action.payload;
    },
    setSortConfig: (state, action) => {
      state.sortConfig = action.payload;
    },
  },
});

export const {
  setSearchResult,
  setCurrentPage,
  setEntriesPerPage,
  setSortConfig,
} = tableSlice.actions;
export default tableSlice.reducer;
